# Generated by Django 5.2 on 2026-01-04 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('athlete_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('athlete_name', models.CharField(blank=True, default='', max_length=255)),
                ('jersey_number', models.CharField(blank=True, default='', max_length=12)),
                ('uniform_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.CharField(choices=[('GK', 'GK'), ('FP', 'FP')], default='FP', max_length=10)),
            ],
            options={
                'db_table': 'athletes',
            },
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_hash', models.CharField(blank=True, default='', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=255)),
                ('parse_status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('error_log', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'data_uploads',
            },
        ),
        migrations.CreateModel(
            name='GpsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date_')),
                ('is_match_day', models.BooleanField(default=False)),
                ('md_offset', models.IntegerField(blank=True, null=True)),
                ('total_duration', models.FloatField(default=0)),
                ('total_distance', models.FloatField(default=0)),
                ('total_player_load', models.FloatField(default=0)),
                ('max_vel', models.FloatField(default=0)),
                ('mean_heart_rate', models.FloatField(blank=True, null=True)),
                ('hsr_distance', models.FloatField(default=0)),
                ('high_decel_count', models.IntegerField(default=0)),
                ('total_dive_count', models.IntegerField(default=0)),
                ('avg_time_to_feet', models.FloatField(blank=True, null=True)),
                ('total_jumps', models.FloatField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily', to='api.athlete')),
            ],
            options={
                'db_table': 'gps_daily',
                'indexes': [models.Index(fields=['date'], name='gps_daily_date__fb9c10_idx'), models.Index(fields=['athlete', 'date'], name='gps_daily_athlete_23d310_idx')],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'date'), name='uniq_gps_daily_athlete_date')],
            },
        ),
        migrations.CreateModel(
            name='GpsSessionRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('date', models.DateField(blank=True, db_column='date_', null=True)),
                ('session_name', models.CharField(blank=True, default='', max_length=255)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_sessions', to='api.athlete')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_rows', to='api.dataupload')),
            ],
            options={
                'db_table': 'gps_sessions_raw',
                'indexes': [models.Index(fields=['upload'], name='gps_session_upload__41af69_idx'), models.Index(fields=['athlete', 'date'], name='gps_session_athlete_3332ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkloadFeaturesDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date_')),
                ('acwr_load', models.FloatField(blank=True, null=True)),
                ('acwr_hsr', models.FloatField(blank=True, null=True)),
                ('acwr_dive', models.FloatField(blank=True, null=True)),
                ('efficiency_index', models.FloatField(blank=True, null=True)),
                ('load_per_meter', models.FloatField(blank=True, null=True)),
                ('monotony_load', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('safety', 'Safety (Green)'), ('caution', 'Caution (Yellow)'), ('risky', 'Risky (Red)')], db_index=True, default='safety', max_length=20)),
                ('risk_reasons', models.JSONField(blank=True, default=list)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workload_features', to='api.athlete')),
            ],
            options={
                'db_table': 'workload_features_daily',
                'indexes': [models.Index(fields=['date'], name='workload_fe_date__081920_idx'), models.Index(fields=['athlete', 'date'], name='workload_fe_athlete_3d187f_idx')],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'date'), name='uniq_workload_features_athlete_date')],
            },
        ),
    ]
