# Generated by Django 5.2 on 2025-10-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTrainingLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.CharField(max_length=50)),
                ('athlete_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('total_distance', models.FloatField()),
                ('acwr', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['athlete_id', 'date'],
                'indexes': [models.Index(fields=['athlete_id', 'date'], name='api_dailytr_athlete_3f6893_idx')],
                'unique_together': {('athlete_id', 'date')},
            },
        ),
    ]
