# Generated by Django 5.2 on 2025-12-19 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('athlete_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('athlete_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'athletes',
            },
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_hash', models.CharField(blank=True, default='', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=255)),
                ('parse_status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('error_log', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'data_uploads',
            },
        ),
        migrations.CreateModel(
            name='GpsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date_')),
                ('is_match_day', models.BooleanField(default=False)),
                ('md_offset', models.IntegerField(blank=True, null=True)),
                ('md_phase', models.CharField(blank=True, default='', max_length=20)),
                ('total_distance', models.FloatField(blank=True, null=True)),
                ('total_player_load', models.FloatField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily', to='workload.athlete')),
            ],
            options={
                'db_table': 'gps_daily',
                'indexes': [models.Index(fields=['date'], name='gps_daily_date__fb9c10_idx'), models.Index(fields=['athlete', 'date'], name='gps_daily_athlete_23d310_idx'), models.Index(fields=['md_phase', 'date'], name='gps_daily_md_phas_36bfb1_idx')],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'date'), name='uniq_gps_daily_athlete_date')],
            },
        ),
        migrations.CreateModel(
            name='GpsSessionRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('date', models.DateField(blank=True, db_column='date_', null=True)),
                ('session_name', models.CharField(blank=True, default='', max_length=255)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_sessions', to='workload.athlete')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_rows', to='workload.dataupload')),
            ],
            options={
                'db_table': 'gps_sessions_raw',
                'indexes': [models.Index(fields=['upload'], name='gps_session_upload__41af69_idx'), models.Index(fields=['athlete', 'date'], name='gps_session_athlete_3332ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkloadFeaturesDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date_')),
                ('ewma7_total_distance', models.FloatField(blank=True, null=True)),
                ('ewma28_total_distance', models.FloatField(blank=True, null=True)),
                ('acwr_ewma_total_distance', models.FloatField(blank=True, null=True)),
                ('ewma7_total_player_load', models.FloatField(blank=True, null=True)),
                ('ewma28_total_player_load', models.FloatField(blank=True, null=True)),
                ('acwr_ewma_total_player_load', models.FloatField(blank=True, null=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workload_features', to='workload.athlete')),
            ],
            options={
                'db_table': 'workload_features_daily',
                'indexes': [models.Index(fields=['date'], name='workload_fe_date__081920_idx'), models.Index(fields=['athlete', 'date'], name='workload_fe_athlete_3d187f_idx')],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'date'), name='uniq_workload_features_athlete_date')],
            },
        ),
    ]
