# Generated by Django 5.2 on 2025-12-19 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('static', 'static'), ('dynamic', 'dynamic')], max_length=20)),
                ('method', models.CharField(default='', max_length=100)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('artifacts', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feature_runs',
                'indexes': [models.Index(fields=['run_type', 'created_at'], name='feature_run_run_typ_916c76_idx')],
            },
        ),
        migrations.CreateModel(
            name='DynamicAnomalyDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date_')),
                ('dyn_error', models.FloatField(blank=True, null=True)),
                ('dyn_thr', models.FloatField(blank=True, null=True)),
                ('dyn_anomaly', models.BooleanField(default=False)),
                ('dyn_streak', models.IntegerField(blank=True, null=True)),
                ('season_block', models.IntegerField(blank=True, null=True)),
                ('season_reset_zone', models.BooleanField(default=False)),
                ('static_anomaly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dynamic_anomalies', to='workload.athlete')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dynamic_rows', to='workload.featurerun')),
            ],
            options={
                'db_table': 'dynamic_anomaly_daily',
                'indexes': [models.Index(fields=['athlete', 'date'], name='dynamic_ano_athlete_9adbde_idx'), models.Index(fields=['date'], name='dynamic_ano_date__6d8426_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'athlete', 'date'), name='uniq_dynamic_run_athlete_date')],
            },
        ),
        migrations.CreateModel(
            name='StaticAnomalyDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date_')),
                ('static_score', models.FloatField(blank=True, null=True)),
                ('static_thr', models.FloatField(blank=True, null=True)),
                ('static_anomaly', models.BooleanField(default=False)),
                ('top_features', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='static_anomalies', to='workload.athlete')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='static_rows', to='workload.featurerun')),
            ],
            options={
                'db_table': 'static_anomaly_daily',
                'indexes': [models.Index(fields=['athlete', 'date'], name='static_anom_athlete_ab1845_idx'), models.Index(fields=['date'], name='static_anom_date__2d7970_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'athlete', 'date'), name='uniq_static_run_athlete_date')],
            },
        ),
    ]
