# Generated by Django 5.2 on 2025-12-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0002_featurerun_dynamicanomalydaily_staticanomalydaily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicanomalydaily',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='dynamicanomalydaily',
            name='run',
        ),
        migrations.RemoveField(
            model_name='staticanomalydaily',
            name='run',
        ),
        migrations.RemoveField(
            model_name='staticanomalydaily',
            name='athlete',
        ),
        migrations.RemoveIndex(
            model_name='gpsdaily',
            name='gps_daily_md_phas_36bfb1_idx',
        ),
        migrations.RemoveField(
            model_name='workloadfeaturesdaily',
            name='acwr_ewma_total_distance',
        ),
        migrations.RemoveField(
            model_name='workloadfeaturesdaily',
            name='acwr_ewma_total_player_load',
        ),
        migrations.RemoveField(
            model_name='workloadfeaturesdaily',
            name='ewma28_total_distance',
        ),
        migrations.RemoveField(
            model_name='workloadfeaturesdaily',
            name='ewma28_total_player_load',
        ),
        migrations.RemoveField(
            model_name='workloadfeaturesdaily',
            name='ewma7_total_distance',
        ),
        migrations.RemoveField(
            model_name='workloadfeaturesdaily',
            name='ewma7_total_player_load',
        ),
        migrations.AddField(
            model_name='gpsdaily',
            name='dive_asymmetry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsdaily',
            name='hsr_distance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gpsdaily',
            name='ima_asymmetry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsdaily',
            name='ima_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gpsdaily',
            name='total_dive_load',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gpsdaily',
            name='total_jumps',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workloadfeaturesdaily',
            name='acwr_dive',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workloadfeaturesdaily',
            name='acwr_hsr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workloadfeaturesdaily',
            name='acwr_jump',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workloadfeaturesdaily',
            name='acwr_total_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workloadfeaturesdaily',
            name='monotony_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workloadfeaturesdaily',
            name='val_asymmetry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsdaily',
            name='total_distance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gpsdaily',
            name='total_player_load',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='DynamicAnomalyDaily',
        ),
        migrations.DeleteModel(
            name='FeatureRun',
        ),
        migrations.DeleteModel(
            name='StaticAnomalyDaily',
        ),
    ]
