# Generated by Django 5.2 on 2025-12-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0003_remove_dynamicanomalydaily_athlete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='position',
            field=models.CharField(choices=[('GK', 'GK'), ('FP', 'FP')], default='FP', max_length=10),
        ),
    ]
